/**
 * 연산자 명령어 핸들러
 */

import type { CommandHandler } from './types';
import { createOperator, createVariable } from './helpers';

/** 단순 연산자 반환 핸들러 생성 */
function operatorHandler(symbol: string): CommandHandler {
  return (ctx) => ({ nodes: [createOperator(symbol)], consumed: ctx.pos });
}

/** 단순 변수 반환 핸들러 생성 */
function variableHandler(symbol: string): CommandHandler {
  return (ctx) => ({ nodes: [createVariable(symbol)], consumed: ctx.pos });
}

/** 연산자 핸들러 레지스트리 */
export const operatorHandlers: Map<string, CommandHandler> = new Map([
  // ─── 기본 연산자 ───────────────────────────────────────
  ['times', operatorHandler('×')],
  ['div', operatorHandler('÷')],
  ['cdot', operatorHandler('·')],
  ['pm', operatorHandler('±')],
  ['mp', operatorHandler('∓')],
  ['ast', operatorHandler('∗')],
  ['star', operatorHandler('⋆')],
  ['circ', operatorHandler('∘')],
  ['bullet', operatorHandler('•')],
  ['diamond', operatorHandler('⋄')],
  ['oplus', operatorHandler('⊕')],
  ['ominus', operatorHandler('⊖')],
  ['otimes', operatorHandler('⊗')],
  ['oslash', operatorHandler('⊘')],
  ['odot', operatorHandler('⊙')],
  ['bigcirc', operatorHandler('○')],
  ['dagger', operatorHandler('†')],
  ['ddagger', operatorHandler('‡')],
  ['vee', operatorHandler('∨')],
  ['wedge', operatorHandler('∧')],
  ['sqcap', operatorHandler('⊓')],
  ['sqcup', operatorHandler('⊔')],
  ['uplus', operatorHandler('⊎')],
  ['triangleleft', operatorHandler('◁')],
  ['triangleright', operatorHandler('▷')],
  ['bigtriangleup', operatorHandler('△')],
  ['bigtriangledown', operatorHandler('▽')],
  ['amalg', operatorHandler('⨿')],
  ['wr', operatorHandler('≀')],
  ['lhd', operatorHandler('⊲')],
  ['rhd', operatorHandler('⊳')],
  ['unlhd', operatorHandler('⊴')],
  ['unrhd', operatorHandler('⊵')],

  // ─── 관계 연산자 ───────────────────────────────────────
  ['ne', operatorHandler('≠')],
  ['neq', operatorHandler('≠')],
  ['le', operatorHandler('≤')],
  ['leq', operatorHandler('≤')],
  ['ge', operatorHandler('≥')],
  ['geq', operatorHandler('≥')],
  ['leqslant', operatorHandler('⩽')],
  ['geqslant', operatorHandler('⩾')],
  ['ll', operatorHandler('≪')],
  ['gg', operatorHandler('≫')],
  ['equiv', operatorHandler('≡')],
  ['sim', operatorHandler('∼')],
  ['simeq', operatorHandler('≃')],
  ['approx', operatorHandler('≈')],
  ['cong', operatorHandler('≅')],
  ['doteq', operatorHandler('≐')],
  ['propto', operatorHandler('∝')],
  ['asymp', operatorHandler('≍')],
  ['prec', operatorHandler('≺')],
  ['succ', operatorHandler('≻')],
  ['preceq', operatorHandler('⪯')],
  ['succeq', operatorHandler('⪰')],
  ['bowtie', operatorHandler('⋈')],
  ['smile', operatorHandler('⌣')],
  ['frown', operatorHandler('⌢')],

  // ─── 집합 연산자 ───────────────────────────────────────
  ['in', operatorHandler('∈')],
  ['ni', operatorHandler('∋')],
  ['notin', operatorHandler('∉')],
  ['subset', operatorHandler('⊂')],
  ['supset', operatorHandler('⊃')],
  ['subseteq', operatorHandler('⊆')],
  ['supseteq', operatorHandler('⊇')],
  ['sqsubseteq', operatorHandler('⊑')],
  ['sqsupseteq', operatorHandler('⊒')],
  ['cup', operatorHandler('∪')],
  ['cap', operatorHandler('∩')],
  ['setminus', operatorHandler('∖')],
  ['vdash', operatorHandler('⊢')],
  ['dashv', operatorHandler('⊣')],
  ['models', operatorHandler('⊨')],

  // ─── 부정 관계 연산자 ──────────────────────────────────
  ['nless', operatorHandler('≮')],
  ['ngtr', operatorHandler('≯')],
  ['nleq', operatorHandler('≰')],
  ['ngeq', operatorHandler('≱')],
  ['nleqslant', operatorHandler('≰')],
  ['ngeqslant', operatorHandler('≱')],
  ['nprec', operatorHandler('⊀')],
  ['nsucc', operatorHandler('⊁')],
  ['npreceq', operatorHandler('⋠')],
  ['nsucceq', operatorHandler('⋡')],
  ['nsubseteq', operatorHandler('⊈')],
  ['nsupseteq', operatorHandler('⊉')],
  ['subsetneq', operatorHandler('⊊')],
  ['supsetneq', operatorHandler('⊋')],
  ['nmid', operatorHandler('∤')],
  ['nparallel', operatorHandler('∦')],
  ['nvdash', operatorHandler('⊬')],
  ['nVdash', operatorHandler('⊮')],
  ['nvDash', operatorHandler('⊭')],
  ['nVDash', operatorHandler('⊯')],
  ['ntriangleleft', operatorHandler('⋪')],
  ['ntriangleright', operatorHandler('⋫')],
  ['ntrianglelefteq', operatorHandler('⋬')],
  ['ntrianglerighteq', operatorHandler('⋭')],
  ['ncong', operatorHandler('≇')],
  ['nsim', operatorHandler('≁')],

  // ─── 논리 연산자 ───────────────────────────────────────
  ['land', operatorHandler('∧')],
  ['lor', operatorHandler('∨')],
  ['lnot', operatorHandler('¬')],
  ['neg', operatorHandler('¬')],
  ['forall', operatorHandler('∀')],
  ['exists', operatorHandler('∃')],
  ['nexists', operatorHandler('∄')],

  // ─── 화살표 ────────────────────────────────────────────
  ['to', operatorHandler('→')],
  ['rightarrow', operatorHandler('→')],
  ['leftarrow', operatorHandler('←')],
  ['leftrightarrow', operatorHandler('↔')],
  ['Rightarrow', operatorHandler('⇒')],
  ['Leftarrow', operatorHandler('⇐')],
  ['Leftrightarrow', operatorHandler('⇔')],
  ['implies', operatorHandler('⟹')],
  ['iff', operatorHandler('⟺')],
  ['mapsto', operatorHandler('↦')],
  ['uparrow', operatorHandler('↑')],
  ['downarrow', operatorHandler('↓')],
  ['longleftarrow', operatorHandler('⟵')],
  ['longrightarrow', operatorHandler('⟶')],
  ['longleftrightarrow', operatorHandler('⟷')],
  ['Longleftarrow', operatorHandler('⟸')],
  ['Longrightarrow', operatorHandler('⟹')],
  ['Longleftrightarrow', operatorHandler('⟺')],
  ['updownarrow', operatorHandler('↕')],
  ['Uparrow', operatorHandler('⇑')],
  ['Downarrow', operatorHandler('⇓')],
  ['Updownarrow', operatorHandler('⇕')],
  ['nearrow', operatorHandler('↗')],
  ['searrow', operatorHandler('↘')],
  ['swarrow', operatorHandler('↙')],
  ['nwarrow', operatorHandler('↖')],
  ['longmapsto', operatorHandler('⟼')],
  ['hookrightarrow', operatorHandler('↪')],
  ['hookleftarrow', operatorHandler('↩')],
  ['rightharpoonup', operatorHandler('⇀')],
  ['rightharpoondown', operatorHandler('⇁')],
  ['leftharpoonup', operatorHandler('↼')],
  ['leftharpoondown', operatorHandler('↽')],
  ['rightleftharpoons', operatorHandler('⇌')],
  ['leftrightharpoons', operatorHandler('⇋')],
  ['dashrightarrow', operatorHandler('⇢')],
  ['dashleftarrow', operatorHandler('⇠')],
  ['twoheadrightarrow', operatorHandler('↠')],
  ['twoheadleftarrow', operatorHandler('↞')],
  ['rightarrowtail', operatorHandler('↣')],
  ['leftarrowtail', operatorHandler('↢')],
  ['rightsquigarrow', operatorHandler('⇝')],
  ['leftrightsquigarrow', operatorHandler('↭')],
  ['curvearrowleft', operatorHandler('↶')],
  ['curvearrowright', operatorHandler('↷')],
  ['circlearrowleft', operatorHandler('↺')],
  ['circlearrowright', operatorHandler('↻')],
  ['Lsh', operatorHandler('↰')],
  ['Rsh', operatorHandler('↱')],
  ['leadsto', operatorHandler('⇝')],

  // ─── 기타 기호 ─────────────────────────────────────────
  ['infty', variableHandler('∞')],
  ['partial', variableHandler('∂')],
  ['nabla', variableHandler('∇')],
  ['prime', variableHandler('′')],
  ['emptyset', variableHandler('\uE000')],
  ['varnothing', variableHandler('∅')],
  ['angle', variableHandler('∠')],
  ['measuredangle', variableHandler('∡')],
  ['perp', operatorHandler('⊥')],
  ['parallel', operatorHandler('∥')],
  ['mid', operatorHandler('∣')],
  ['backslash', variableHandler('∖')],
  ['aleph', variableHandler('ℵ')],
  ['wp', variableHandler('℘')],
  ['Re', variableHandler('ℜ')],
  ['Im', variableHandler('ℑ')],
  ['ell', variableHandler('ℓ')],
  ['hbar', variableHandler('ℏ')],
  ['imath', variableHandler('\u{1D6A4}')],
  ['jmath', variableHandler('\u{1D6A5}')],
  ['clubsuit', variableHandler('♣')],
  ['diamondsuit', variableHandler('♢')],
  ['heartsuit', variableHandler('♡')],
  ['spadesuit', variableHandler('♠')],
  ['triangle', variableHandler('△')],
  ['square', variableHandler('□')],

  // ─── 구분자 (standalone) ─────────────────────────────────
  ['langle', operatorHandler('⟨')],
  ['rangle', operatorHandler('⟩')],
  ['lceil', operatorHandler('⌈')],
  ['rceil', operatorHandler('⌉')],
  ['lfloor', operatorHandler('⌊')],
  ['rfloor', operatorHandler('⌋')],
  ['lvert', operatorHandler('|')],
  ['rvert', operatorHandler('|')],
  ['lVert', operatorHandler('‖')],
  ['rVert', operatorHandler('‖')],
  ['vert', operatorHandler('|')],
  ['Vert', operatorHandler('‖')],

  // ─── 추가 기호 ─────────────────────────────────────────
  ['sharp', operatorHandler('♯')],
  ['flat', operatorHandler('♭')],
  ['natural', operatorHandler('♮')],
  ['colon', operatorHandler(':')],
  ['top', operatorHandler('⊤')],
  ['bot', operatorHandler('⊥')],

  // ─── 점 기호 ───────────────────────────────────────────
  ['ldots', operatorHandler('…')],
  ['cdots', operatorHandler('⋯')],
  ['vdots', operatorHandler('⋮')],
  ['ddots', operatorHandler('⋱')],
  ['dots', operatorHandler('…')],
]);
